@startuml
title Difference-Progression\n

'States
state "Initial collection (C0)" as C0 #white: Initial collection

state "After modification 1 (C0M1)" as C0M1 #white: Initial collection after modification 1

state "After modification 2 (C0M2)" as C0M2 #white: Initial collection after modification 2

state Diff0C1 #lightgreen: Difference from initial collection
Diff0C1: to collection after modification 2

state Diff0C2 #lightgreen: Difference from initial collection
Diff0C2: to collection after modification 2

state DiffC1C2 #lightgreen: Difference from collection after modification 1
DiffC1C2: to collection after modification 2

state "Difference Progression (DiffP0C1C2)" as DiffP0C1C2 #lightblue: Difference progression from modification 1 to modification 2
DiffP0C1C2: (with initial collection as base)


'Edges
C0 --> Diff0C1
C0 --> Diff0C2

Diff0C1 --> C0M1
Diff0C2 --> C0M2

Diff0C1 -> DiffP0C1C2
DiffP0C1C2 -> Diff0C2
C0 -[dashed]-> DiffP0C1C2
note on link
A difference progression
always has a base collection.
end note
DiffP0C1C2 -[dashed]-> DiffC1C2
note on link
The difference progression
is identical to DiffC1C2.
end note

C0M1 -> DiffC1C2
DiffC1C2 -> C0M2
@enduml